### PR TITLE
Nethandler issue 205

### PR DESCRIPTION
**Pull request by jwmelto**
This PR cleans up the platform-dependent code in network.h that led to #205. It also starts to reduce the profligate including of headers that makes this code base such a mess.

The basic issue is that there was a logic hole in all the #ifdefs that allowed a Linux system to define `AddrLen` as `int` instead of as `socklen_t`

It has not been astyled; I'll take that criticism if levied. I'd like to figure out a way to enforce it and not rely on the good manners of developers.

As usual, I probably went farther than a single PR should

### CODE REVIEW

**Comment by allejo** [comment]
This branch is failing to build for me on Ubuntu 16.04

```
multicast.cxx: In function ‘int openBroadcast(int, const char*, sockaddr_in*)’:
multicast.cxx:149:19: error: aggregate ‘openBroadcast(int, const char*, sockaddr_in*)::ifconf conf’ has incomplete type and cannot be defined
     struct ifconf conf;
                   ^
multicast.cxx:150:35: error: elements of array ‘openBroadcast(int, const char*, sockaddr_in*)::ifreq req [5]’ have incomplete type
     struct ifreq req[numInterfaces];
                                   ^
multicast.cxx:150:35: error: storage size of ‘req’ isn’t known
multicast.cxx:157:19: error: ‘SIOCGIFCONF’ was not declared in this scope
     if (ioctl(fd, SIOCGIFCONF, &conf) < 0)
                   ^
multicast.cxx:157:37: error: ‘ioctl’ was not declared in this scope
     if (ioctl(fd, SIOCGIFCONF, &conf) < 0)
                                     ^
multicast.cxx:172:23: error: ‘SIOCGIFBRDADDR’ was not declared in this scope
         if (ioctl(fd, SIOCGIFBRDADDR, req + i) < 0)
                       ^
multicast.cxx:172:46: error: ‘ioctl’ was not declared in this scope
         if (ioctl(fd, SIOCGIFBRDADDR, req + i) < 0)
```

**Comment by jwmelto** [comment]
Thanks for another platform. Is that the only error?

**Comment by allejo** [comment]
I'm not sure if there are more errors, that error stops all further compilation if that's what you mean.

This builds fine for me on macOS; don't have a Windows machine to test on

**Comment by jwmelto** [comment]
can you run "make -k"? That should keep going unless the error precludes further building for a given target

**Comment by allejo** [comment]
TIL about `make -k`, that's awesome!

Here's some more:

```
ServerList.cxx: In member function ‘void ServerList::readServerList()’:
ServerList.cxx:86:66: error: ‘strlen’ was not declared in this scope
         if (strncmp(base, tokenIdentifier, strlen(tokenIdentifier)) == 0)
                                                                  ^
ServerList.cxx:86:67: error: ‘strncmp’ was not declared in this scope
         if (strncmp(base, tokenIdentifier, strlen(tokenIdentifier)) == 0)
                                                                   ^
ServerList.cxx:89:33: error: ‘strncpy’ was not declared in this scope
                     TokenLen - 1);
                                 ^
ServerList.cxx:103:52: error: ‘strcpy’ was not declared in this scope
             strcpy(startupInfo->token, "badtoken\0");
                                                    ^
ServerList.cxx:110:52: error: ‘strcpy’ was not declared in this scope
             strcpy(startupInfo->token, "badtoken\0");
                                                    ^
ServerList.cxx:138:33: error: ‘strchr’ was not declared in this scope
         scan2 = strchr(name, ':');
                                 ^
ServerList.cxx:146:47: error: ‘strcmp’ was not declared in this scope
         if (strcmp(version, getServerVersion()) == 0 &&
                                               ^
ServerList.cxx:147:39: error: ‘strlen’ was not declared in this scope
                 (int)strlen(infoServer) == PingPacketHexPackedSize &&
                                       ^
ServerList.cxx:199:34: error: ‘memmove’ was not declared in this scope
     memmove(theData, base, theLen);
                                  ^
Makefile:482: recipe for target 'ServerList.lo' failed
```

```
bzfsAPI.cxx: In function ‘bool bz_getNearestFlagSafetyZone(int, float*)’:
bzfsAPI.cxx:2944:15: warning: declaration of ‘team’ shadows a global declaration [-Wshadow]
     TeamColor team = flagInfo->teamIndex();
               ^
In file included from bzfsAPI.cxx:19:0:
bzfs.h:139:21: note: shadowed declaration is here
 extern TeamInfo     team[NumTeams];
```

**Comment by jwmelto** [comment]
The `bzfsAPI` one is odd. I didn't touch that file, and the only headers I touched were Ping, ServerItem, and network. I'm not sure how that warning could have been introduced.

**Comment by allejo** [comment]
@blast007, does this successfully build/work on Windows?

**Comment by blast007** [comment]
It built and ran fine for me on Windows with Visual Studio 2017, but fails to build on Debian Buster (gcc 8.3.0):
```
Making all in net
make[2]: Entering directory '/home/user/bzflag-jwmelto-nethandler-issue-205/src/net'
depbase=`echo multicast.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../../libtool --silent  --tag=CXX  --silent --mode=compile ccache g++ -DHAVE_CONFIG_H -I. -I../../include   -I../../include  -Wall -Wextra -Wcast-qual -Wredundant-decls -Wshadow -Wundef -pedantic -mtune=native -fsigned-char -Werror -g -O0   -MT multicast.lo -MD -MP -MF $depbase.Tpo -c -o multicast.lo multicast.cxx &&\
mv -f $depbase.Tpo $depbase.Plo
multicast.cxx: In function ‘int openBroadcast(int, const char*, sockaddr_in*)’:
multicast.cxx:133:19: error: aggregate ‘openBroadcast(int, const char*, sockaddr_in*)::ifconf conf’ has incomplete type and cannot be defined
     struct ifconf conf;
                   ^~~~
multicast.cxx:134:18: error: elements of array ‘openBroadcast(int, const char*, sockaddr_in*)::ifreq req [5]’ have incomplete type
     struct ifreq req[numInterfaces];
                  ^~~
multicast.cxx:134:18: error: storage size of ‘req’ isn’t known
```

**Comment by sodomon2** [comment]
Apparently the error NetHandler.cxx no longer gives it but now gives one different here the other error

e=native -fsigned-char -fexpensive-optimizations  -g -O2 -MT multicast.lo -MD -MP -MF $depbase.Tpo -c -o multicast.lo multicast.cxx &&\
mv -f $depbase.Tpo $depbase.Plo
multicast.cxx: In function 'int openBroadcast(int, const char*, sockaddr_in*)':
multicast.cxx:133:19: error: aggregate 'openBroadcast(int, const char*, sockaddr_in*)::ifconf conf' has incomplete type and cannot be defined
     struct ifconf conf;
                   ^~~~
multicast.cxx:134:18: error: elements of array 'openBroadcast(int, const char*, sockaddr_in*)::ifreq req [5]' have incomplete type
     struct ifreq req[numInterfaces];
                  ^~~
multicast.cxx:134:18: error: storage size of 'req' isn't known

**Comment by jwmelto** [comment]
> in multicast.cxx line 133
> 
> replace this with this
> 
> ```
> #if defined(__linux__)
> ```
> 
> for this reason
> 
> ```
> #if ( defined(__linux__) && defined(__GLIBC__) )
> ```

Are you suggesting that the device navigation logic is GLIBC-specific? It's not enough just to have it compile; you'll want it to actually work as well.

I have plenty of concerns about the networking code in general and this so-called multicast in particular, but I don't know that just dropping that block for Alpine (and any other non-GLIBC Linuxen) is necessarily a good idea.

**Comment by blast007** [comment]
This builds and works on Linux and Windows for me.

**Comment by sodomon2** [comment]
already compiles without the need to patch and now compiles without errors
