### ISSUE TITLE
Unit tests fail to build on Debian Jessie GCC 4.9.2

### ISSUE THREAD

**Issue by blast007** [BZFlag-Dev/bzflag#11]
When building the test cases on Debian Jessie (via 'make check'), which has GCC 4.9.2 and either the 3.7.1 release or the bleeding edge git of CppUTest (installed system-wide with 'make install'), the build fails with:
```Text
make[1]: Entering directory '/home/user/bzflag/tests'
g++ -DHAVE_CONFIG_H -I. -I../include  -I../src/bzfs  -I../include  -lCppUTest -std=c++0x -MT unittests-tests.o -MD -MP -MF .deps/unittests-tests.Tpo -c -o unittests-tests.o `test -f 'tests.cxx' || echo './'`tests.cxx
mv -f .deps/unittests-tests.Tpo .deps/unittests-tests.Po
g++ -DHAVE_CONFIG_H -I. -I../include  -I../src/bzfs  -I../include  -lCppUTest -std=c++0x -MT unittests-bans.o -MD -MP -MF .deps/unittests-bans.Tpo -c -o unittests-bans.o `test -f 'bans.cxx' || echo './'`bans.cxx
In file included from /usr/include/c++/4.9/map:60:0,
                 from ../include/StateDatabase.h:21,
                 from ../include/global.h:26,
                 from ../include/Address.h:31,
                 from ../src/bzfs/AccessControlList.h:21,
                 from bans.cxx:15:
/usr/include/c++/4.9/bits/stl_tree.h: In member function 'std::_Rb_tree_node<_Val>* std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_create_node(_Args&& ...)':
/usr/include/c++/4.9/bits/stl_tree.h:420:14: error: '__tmp' does not name a type
        ::new(__tmp) _Rb_tree_node<_Val>;
              ^
Makefile:501: recipe for target 'unittests-bans.o' failed
make[1]: *** [unittests-bans.o] Error 1
make[1]: Leaving directory '/home/user/bzflag/tests'
Makefile:486: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

The build works fine on Debian Wheezy, which has GCC 4.7.2.  Am I hitting a GCC 4.9 bug, or is our code messing something up?  One thing to note is that it seems the issue may be triggered by building in c++0x mode.

**Comment by blast007** [comment]
I managed to reproduce the issue in a very minimal and standalone example.

```c++
#include "CppUTest/CommandLineTestRunner.h"
#include <map>

TEST_GROUP(Basic) {};
TEST(Basic, BasicCompareison)
{
  CHECK_TEXT(1 == 1, "Alternate reality detected");
}

int main(int ac, const char** av)
{
  return CommandLineTestRunner::RunAllTests(ac, av);
}
```
Name it test.cxx and try to build it using:
```bash
g++ -I. -lCppUTest -std=c++0x -MT unittests-tests.o -MD -MP -MF .deps/unittests-tests.Tpo -c -o unittests-tests.o `test -f 'tests.cxx'
```
That results in:
```
In file included from /usr/include/c++/4.9/map:60:0,
                 from tests.cxx:2:
/usr/include/c++/4.9/bits/stl_tree.h: In member function ‘std::_Rb_tree_node<_Val>* std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_create_node(_Args&& ...)’:
/usr/include/c++/4.9/bits/stl_tree.h:420:14: error: ‘__tmp’ does not name a type
        ::new(__tmp) _Rb_tree_node<_Val>;
              ^
```
However, if I move the include for <map> above the include for CppUTest/CommandLineTestRunner.h, then it works.
