### PR TITLE
Fix missing include

### PR DESCRIPTION
**Pull request by h3xx**
Causes issues in newer versions of GCC.

Broken since aa19b4eb0b064bc8e83b47337916d5caedd0bcac

### CODE REVIEW

**Comment by macsforme** [comment]
Which functions/types require this additional header? The original author and I are both on macOS with Xcode/clang, and I’m not getting any error at the moment.

**Comment by blast007** [comment]
With gcc 6.3.0:
```
TimeKeeper.cxx: In static member function ‘static const char* TimeKeeper::timestamp()’:
TimeKeeper.cxx:99:91: error: ‘strncpy’ was not declared in this scope
                                       now->tm_hour, now->tm_min, now->tm_sec).c_str(), 256);
                                                                                           ^
```

**Comment by blast007** [comment]
The PR has been merged.  Thanks!
